In [51]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('image.jpg')
print(img.dtype)
height, width, _ = img.shape

cv2.imshow("Image", img)
cv2.waitKey()

uint8


-1

In [52]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow("Gray", gray)
# cv2.waitKey()

In [53]:
blur = cv2.GaussianBlur(gray, (15, 15), 1)
# cv2.imshow("Blur", blur)
# cv2.waitKey()

In [54]:
edge = cv2.Canny(blur, 50, 150)
# cv2.imshow("Edge", edge)
# cv2.waitKey()

In [55]:
lines = cv2.HoughLines(edge, 1, np.pi/180, 150)
print(lines.shape)
print(lines)
for line in lines:

    rho,theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 400*(-b))
    y1 = int(y0 + 400*(a))
    x2 = int(x0 - 400*(-b))
    y2 = int(y0 - 400*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),1)

(97, 1, 2)
[[[ 3.0900000e+02  1.5707964e+00]]

 [[-2.7500000e+02  2.3736477e+00]]

 [[ 2.5800000e+02  8.3775806e-01]]

 [[-2.7800000e+02  2.3736477e+00]]

 [[ 2.6300000e+02  0.0000000e+00]]

 [[-2.6700000e+02  2.3561945e+00]]

 [[ 2.8000000e+02  9.7738439e-01]]

 [[ 4.8700000e+02  0.0000000e+00]]

 [[ 4.1300000e+02  0.0000000e+00]]

 [[ 2.8300000e+02  9.5993108e-01]]

 [[-1.7800000e+02  2.2340214e+00]]

 [[ 2.6200000e+02  8.5521132e-01]]

 [[ 2.6000000e+02  8.2030475e-01]]

 [[ 2.6000000e+02  2.0245819e+00]]

 [[-1.7500000e+02  2.2340214e+00]]

 [[-2.5600000e+02  2.3387411e+00]]

 [[ 3.8700000e+02  0.0000000e+00]]

 [[ 4.1600000e+02  0.0000000e+00]]

 [[ 4.6300000e+02  0.0000000e+00]]

 [[ 2.9500000e+02  1.7627826e+00]]

 [[-1.6700000e+02  2.2165682e+00]]

 [[ 3.1300000e+02  1.5707964e+00]]

 [[-2.6900000e+02  2.3561945e+00]]

 [[ 3.9800000e+02  0.0000000e+00]]

 [[ 2.8300000e+02  9.9483764e-01]]

 [[ 2.9900000e+02  1.7453293e+00]]

 [[ 3.0200000e+02  1.7453293e+00]]

 [[ 2.6500000e+02

In [57]:
lines = cv2.HoughLinesP(edge, 1, np.pi/180, 30, maxLineGap=250)      # Return coordinates of the detected liens
print(lines.shape, lines)
for line in lines:
   x1, y1, x2, y2 = line[0]
   cv2.line(img, (x1, y1), (x2, y2), (0, 0, 255), 1)

In [60]:
cv2.imshow("image", img)
cv2.waitKey()

-1